/**
 * СОБРАНО СКРИПТОМ — руками не править: node scripts/build-pet-frames.mjs
 *
 * Кадры облика «cat» (Синапс 2). Листы 7×8 лежат в
 * ~/dev/psygames-astro/_sync/synapse-v2/cat, нарезка — build_pack.py там же.
 *
 * CAT_FRAMES — состояния анимации: ряд = цикл, 7 фаз, последняя
 * смыкается с первой.
 * CAT_LOOK — шкалы внешности: ряд НЕ анимация, из него берут ОДИН кадр по
 * состоянию заботы (см. src/services/petLook.ts).
 */
export const CAT_FRAMES: Record<string, any[]> = {
  celebrate: [
    require('@/assets/images/pet/cat/celebrate0.webp'),
    require('@/assets/images/pet/cat/celebrate1.webp'),
    require('@/assets/images/pet/cat/celebrate2.webp'),
    require('@/assets/images/pet/cat/celebrate3.webp'),
    require('@/assets/images/pet/cat/celebrate4.webp'),
    require('@/assets/images/pet/cat/celebrate5.webp'),
    require('@/assets/images/pet/cat/celebrate6.webp'),
  ],
  cheer: [
    require('@/assets/images/pet/cat/cheer0.webp'),
    require('@/assets/images/pet/cat/cheer1.webp'),
    require('@/assets/images/pet/cat/cheer2.webp'),
    require('@/assets/images/pet/cat/cheer3.webp'),
    require('@/assets/images/pet/cat/cheer4.webp'),
    require('@/assets/images/pet/cat/cheer5.webp'),
    require('@/assets/images/pet/cat/cheer6.webp'),
  ],
  curious: [
    require('@/assets/images/pet/cat/curious0.webp'),
    require('@/assets/images/pet/cat/curious1.webp'),
    require('@/assets/images/pet/cat/curious2.webp'),
    require('@/assets/images/pet/cat/curious3.webp'),
    require('@/assets/images/pet/cat/curious4.webp'),
    require('@/assets/images/pet/cat/curious5.webp'),
    require('@/assets/images/pet/cat/curious6.webp'),
  ],
  dance: [
    require('@/assets/images/pet/cat/dance0.webp'),
    require('@/assets/images/pet/cat/dance1.webp'),
    require('@/assets/images/pet/cat/dance2.webp'),
    require('@/assets/images/pet/cat/dance3.webp'),
    require('@/assets/images/pet/cat/dance4.webp'),
    require('@/assets/images/pet/cat/dance5.webp'),
    require('@/assets/images/pet/cat/dance6.webp'),
  ],
  earflick: [
    require('@/assets/images/pet/cat/earflick0.webp'),
    require('@/assets/images/pet/cat/earflick1.webp'),
    require('@/assets/images/pet/cat/earflick2.webp'),
    require('@/assets/images/pet/cat/earflick3.webp'),
    require('@/assets/images/pet/cat/earflick4.webp'),
    require('@/assets/images/pet/cat/earflick5.webp'),
    require('@/assets/images/pet/cat/earflick6.webp'),
  ],
  eat: [
    require('@/assets/images/pet/cat/eat0.webp'),
    require('@/assets/images/pet/cat/eat1.webp'),
    require('@/assets/images/pet/cat/eat2.webp'),
    require('@/assets/images/pet/cat/eat3.webp'),
    require('@/assets/images/pet/cat/eat4.webp'),
    require('@/assets/images/pet/cat/eat5.webp'),
    require('@/assets/images/pet/cat/eat6.webp'),
  ],
  groom: [
    require('@/assets/images/pet/cat/groom0.webp'),
    require('@/assets/images/pet/cat/groom1.webp'),
    require('@/assets/images/pet/cat/groom2.webp'),
    require('@/assets/images/pet/cat/groom3.webp'),
    require('@/assets/images/pet/cat/groom4.webp'),
    require('@/assets/images/pet/cat/groom5.webp'),
    require('@/assets/images/pet/cat/groom6.webp'),
  ],
  idle: [
    require('@/assets/images/pet/cat/idle0.webp'),
    require('@/assets/images/pet/cat/idle1.webp'),
    require('@/assets/images/pet/cat/idle2.webp'),
    require('@/assets/images/pet/cat/idle3.webp'),
    require('@/assets/images/pet/cat/idle4.webp'),
    require('@/assets/images/pet/cat/idle5.webp'),
    require('@/assets/images/pet/cat/idle6.webp'),
  ],
  jump: [
    require('@/assets/images/pet/cat/jump0.webp'),
    require('@/assets/images/pet/cat/jump1.webp'),
    require('@/assets/images/pet/cat/jump2.webp'),
    require('@/assets/images/pet/cat/jump3.webp'),
    require('@/assets/images/pet/cat/jump4.webp'),
    require('@/assets/images/pet/cat/jump5.webp'),
    require('@/assets/images/pet/cat/jump6.webp'),
  ],
  lookaround: [
    require('@/assets/images/pet/cat/lookaround0.webp'),
    require('@/assets/images/pet/cat/lookaround1.webp'),
    require('@/assets/images/pet/cat/lookaround2.webp'),
    require('@/assets/images/pet/cat/lookaround3.webp'),
    require('@/assets/images/pet/cat/lookaround4.webp'),
    require('@/assets/images/pet/cat/lookaround5.webp'),
    require('@/assets/images/pet/cat/lookaround6.webp'),
  ],
  point: [
    require('@/assets/images/pet/cat/point0.webp'),
    require('@/assets/images/pet/cat/point1.webp'),
    require('@/assets/images/pet/cat/point2.webp'),
    require('@/assets/images/pet/cat/point3.webp'),
    require('@/assets/images/pet/cat/point4.webp'),
    require('@/assets/images/pet/cat/point5.webp'),
    require('@/assets/images/pet/cat/point6.webp'),
  ],
  proud: [
    require('@/assets/images/pet/cat/proud0.webp'),
    require('@/assets/images/pet/cat/proud1.webp'),
    require('@/assets/images/pet/cat/proud2.webp'),
    require('@/assets/images/pet/cat/proud3.webp'),
    require('@/assets/images/pet/cat/proud4.webp'),
    require('@/assets/images/pet/cat/proud5.webp'),
    require('@/assets/images/pet/cat/proud6.webp'),
  ],
  sad: [
    require('@/assets/images/pet/cat/sad0.webp'),
    require('@/assets/images/pet/cat/sad1.webp'),
    require('@/assets/images/pet/cat/sad2.webp'),
    require('@/assets/images/pet/cat/sad3.webp'),
    require('@/assets/images/pet/cat/sad4.webp'),
    require('@/assets/images/pet/cat/sad5.webp'),
    require('@/assets/images/pet/cat/sad6.webp'),
  ],
  scratch: [
    require('@/assets/images/pet/cat/scratch0.webp'),
    require('@/assets/images/pet/cat/scratch1.webp'),
    require('@/assets/images/pet/cat/scratch2.webp'),
    require('@/assets/images/pet/cat/scratch3.webp'),
    require('@/assets/images/pet/cat/scratch4.webp'),
    require('@/assets/images/pet/cat/scratch5.webp'),
    require('@/assets/images/pet/cat/scratch6.webp'),
  ],
  sleep: [
    require('@/assets/images/pet/cat/sleep0.webp'),
    require('@/assets/images/pet/cat/sleep1.webp'),
    require('@/assets/images/pet/cat/sleep2.webp'),
    require('@/assets/images/pet/cat/sleep3.webp'),
    require('@/assets/images/pet/cat/sleep4.webp'),
    require('@/assets/images/pet/cat/sleep5.webp'),
    require('@/assets/images/pet/cat/sleep6.webp'),
  ],
  sleepback: [
    require('@/assets/images/pet/cat/sleepback0.webp'),
    require('@/assets/images/pet/cat/sleepback1.webp'),
    require('@/assets/images/pet/cat/sleepback2.webp'),
    require('@/assets/images/pet/cat/sleepback3.webp'),
    require('@/assets/images/pet/cat/sleepback4.webp'),
    require('@/assets/images/pet/cat/sleepback5.webp'),
    require('@/assets/images/pet/cat/sleepback6.webp'),
  ],
  sleepcurl: [
    require('@/assets/images/pet/cat/sleepcurl0.webp'),
    require('@/assets/images/pet/cat/sleepcurl1.webp'),
    require('@/assets/images/pet/cat/sleepcurl2.webp'),
    require('@/assets/images/pet/cat/sleepcurl3.webp'),
    require('@/assets/images/pet/cat/sleepcurl4.webp'),
    require('@/assets/images/pet/cat/sleepcurl5.webp'),
    require('@/assets/images/pet/cat/sleepcurl6.webp'),
  ],
  sleepdrool: [
    require('@/assets/images/pet/cat/sleepdrool0.webp'),
    require('@/assets/images/pet/cat/sleepdrool1.webp'),
    require('@/assets/images/pet/cat/sleepdrool2.webp'),
    require('@/assets/images/pet/cat/sleepdrool3.webp'),
    require('@/assets/images/pet/cat/sleepdrool4.webp'),
    require('@/assets/images/pet/cat/sleepdrool5.webp'),
    require('@/assets/images/pet/cat/sleepdrool6.webp'),
  ],
  sleepface: [
    require('@/assets/images/pet/cat/sleepface0.webp'),
    require('@/assets/images/pet/cat/sleepface1.webp'),
    require('@/assets/images/pet/cat/sleepface2.webp'),
    require('@/assets/images/pet/cat/sleepface3.webp'),
    require('@/assets/images/pet/cat/sleepface4.webp'),
    require('@/assets/images/pet/cat/sleepface5.webp'),
    require('@/assets/images/pet/cat/sleepface6.webp'),
  ],
  sleephalf: [
    require('@/assets/images/pet/cat/sleephalf0.webp'),
    require('@/assets/images/pet/cat/sleephalf1.webp'),
    require('@/assets/images/pet/cat/sleephalf2.webp'),
    require('@/assets/images/pet/cat/sleephalf3.webp'),
    require('@/assets/images/pet/cat/sleephalf4.webp'),
    require('@/assets/images/pet/cat/sleephalf5.webp'),
    require('@/assets/images/pet/cat/sleephalf6.webp'),
  ],
  sleeploaf: [
    require('@/assets/images/pet/cat/sleeploaf0.webp'),
    require('@/assets/images/pet/cat/sleeploaf1.webp'),
    require('@/assets/images/pet/cat/sleeploaf2.webp'),
    require('@/assets/images/pet/cat/sleeploaf3.webp'),
    require('@/assets/images/pet/cat/sleeploaf4.webp'),
    require('@/assets/images/pet/cat/sleeploaf5.webp'),
    require('@/assets/images/pet/cat/sleeploaf6.webp'),
  ],
  sleepside: [
    require('@/assets/images/pet/cat/sleepside0.webp'),
    require('@/assets/images/pet/cat/sleepside1.webp'),
    require('@/assets/images/pet/cat/sleepside2.webp'),
    require('@/assets/images/pet/cat/sleepside3.webp'),
    require('@/assets/images/pet/cat/sleepside4.webp'),
    require('@/assets/images/pet/cat/sleepside5.webp'),
    require('@/assets/images/pet/cat/sleepside6.webp'),
  ],
  sneeze: [
    require('@/assets/images/pet/cat/sneeze0.webp'),
    require('@/assets/images/pet/cat/sneeze1.webp'),
    require('@/assets/images/pet/cat/sneeze2.webp'),
    require('@/assets/images/pet/cat/sneeze3.webp'),
    require('@/assets/images/pet/cat/sneeze4.webp'),
    require('@/assets/images/pet/cat/sneeze5.webp'),
    require('@/assets/images/pet/cat/sneeze6.webp'),
  ],
  stretch: [
    require('@/assets/images/pet/cat/stretch0.webp'),
    require('@/assets/images/pet/cat/stretch1.webp'),
    require('@/assets/images/pet/cat/stretch2.webp'),
    require('@/assets/images/pet/cat/stretch3.webp'),
    require('@/assets/images/pet/cat/stretch4.webp'),
    require('@/assets/images/pet/cat/stretch5.webp'),
    require('@/assets/images/pet/cat/stretch6.webp'),
  ],
  surprise: [
    require('@/assets/images/pet/cat/surprise0.webp'),
    require('@/assets/images/pet/cat/surprise1.webp'),
    require('@/assets/images/pet/cat/surprise2.webp'),
    require('@/assets/images/pet/cat/surprise3.webp'),
    require('@/assets/images/pet/cat/surprise4.webp'),
    require('@/assets/images/pet/cat/surprise5.webp'),
    require('@/assets/images/pet/cat/surprise6.webp'),
  ],
  tailchase: [
    require('@/assets/images/pet/cat/tailchase0.webp'),
    require('@/assets/images/pet/cat/tailchase1.webp'),
    require('@/assets/images/pet/cat/tailchase2.webp'),
    require('@/assets/images/pet/cat/tailchase3.webp'),
    require('@/assets/images/pet/cat/tailchase4.webp'),
    require('@/assets/images/pet/cat/tailchase5.webp'),
    require('@/assets/images/pet/cat/tailchase6.webp'),
  ],
  turnaround: [
    require('@/assets/images/pet/cat/turnaround0.webp'),
    require('@/assets/images/pet/cat/turnaround1.webp'),
    require('@/assets/images/pet/cat/turnaround2.webp'),
    require('@/assets/images/pet/cat/turnaround3.webp'),
    require('@/assets/images/pet/cat/turnaround4.webp'),
    require('@/assets/images/pet/cat/turnaround5.webp'),
    require('@/assets/images/pet/cat/turnaround6.webp'),
  ],
  wake: [
    require('@/assets/images/pet/cat/wake0.webp'),
    require('@/assets/images/pet/cat/wake1.webp'),
    require('@/assets/images/pet/cat/wake2.webp'),
    require('@/assets/images/pet/cat/wake3.webp'),
    require('@/assets/images/pet/cat/wake4.webp'),
    require('@/assets/images/pet/cat/wake5.webp'),
    require('@/assets/images/pet/cat/wake6.webp'),
  ],
  walk: [
    require('@/assets/images/pet/cat/walk0.webp'),
    require('@/assets/images/pet/cat/walk1.webp'),
    require('@/assets/images/pet/cat/walk2.webp'),
    require('@/assets/images/pet/cat/walk3.webp'),
    require('@/assets/images/pet/cat/walk4.webp'),
    require('@/assets/images/pet/cat/walk5.webp'),
    require('@/assets/images/pet/cat/walk6.webp'),
  ],
  wave: [
    require('@/assets/images/pet/cat/wave0.webp'),
    require('@/assets/images/pet/cat/wave1.webp'),
    require('@/assets/images/pet/cat/wave2.webp'),
    require('@/assets/images/pet/cat/wave3.webp'),
    require('@/assets/images/pet/cat/wave4.webp'),
    require('@/assets/images/pet/cat/wave5.webp'),
    require('@/assets/images/pet/cat/wave6.webp'),
  ],
  wiggle: [
    require('@/assets/images/pet/cat/wiggle0.webp'),
    require('@/assets/images/pet/cat/wiggle1.webp'),
    require('@/assets/images/pet/cat/wiggle2.webp'),
    require('@/assets/images/pet/cat/wiggle3.webp'),
    require('@/assets/images/pet/cat/wiggle4.webp'),
    require('@/assets/images/pet/cat/wiggle5.webp'),
    require('@/assets/images/pet/cat/wiggle6.webp'),
  ],
  yawn: [
    require('@/assets/images/pet/cat/yawn0.webp'),
    require('@/assets/images/pet/cat/yawn1.webp'),
    require('@/assets/images/pet/cat/yawn2.webp'),
    require('@/assets/images/pet/cat/yawn3.webp'),
    require('@/assets/images/pet/cat/yawn4.webp'),
    require('@/assets/images/pet/cat/yawn5.webp'),
    require('@/assets/images/pet/cat/yawn6.webp'),
  ],
};

export const CAT_LOOK: Record<string, any[]> = {
  age: [
    require('@/assets/images/pet/cat/care_age0.webp'),
    require('@/assets/images/pet/cat/care_age1.webp'),
    require('@/assets/images/pet/cat/care_age2.webp'),
    require('@/assets/images/pet/cat/care_age3.webp'),
    require('@/assets/images/pet/cat/care_age4.webp'),
    require('@/assets/images/pet/cat/care_age5.webp'),
    require('@/assets/images/pet/cat/care_age6.webp'),
  ],
  clean: [
    require('@/assets/images/pet/cat/care_clean0.webp'),
    require('@/assets/images/pet/cat/care_clean1.webp'),
    require('@/assets/images/pet/cat/care_clean2.webp'),
    require('@/assets/images/pet/cat/care_clean3.webp'),
    require('@/assets/images/pet/cat/care_clean4.webp'),
    require('@/assets/images/pet/cat/care_clean5.webp'),
    require('@/assets/images/pet/cat/care_clean6.webp'),
  ],
  coat: [
    require('@/assets/images/pet/cat/care_coat0.webp'),
    require('@/assets/images/pet/cat/care_coat1.webp'),
    require('@/assets/images/pet/cat/care_coat2.webp'),
    require('@/assets/images/pet/cat/care_coat3.webp'),
    require('@/assets/images/pet/cat/care_coat4.webp'),
    require('@/assets/images/pet/cat/care_coat5.webp'),
    require('@/assets/images/pet/cat/care_coat6.webp'),
  ],
  energy: [
    require('@/assets/images/pet/cat/care_energy0.webp'),
    require('@/assets/images/pet/cat/care_energy1.webp'),
    require('@/assets/images/pet/cat/care_energy2.webp'),
    require('@/assets/images/pet/cat/care_energy3.webp'),
    require('@/assets/images/pet/cat/care_energy4.webp'),
    require('@/assets/images/pet/cat/care_energy5.webp'),
    require('@/assets/images/pet/cat/care_energy6.webp'),
  ],
  glow: [
    require('@/assets/images/pet/cat/care_glow0.webp'),
    require('@/assets/images/pet/cat/care_glow1.webp'),
    require('@/assets/images/pet/cat/care_glow2.webp'),
    require('@/assets/images/pet/cat/care_glow3.webp'),
    require('@/assets/images/pet/cat/care_glow4.webp'),
    require('@/assets/images/pet/cat/care_glow5.webp'),
    require('@/assets/images/pet/cat/care_glow6.webp'),
  ],
  health: [
    require('@/assets/images/pet/cat/care_health0.webp'),
    require('@/assets/images/pet/cat/care_health1.webp'),
    require('@/assets/images/pet/cat/care_health2.webp'),
    require('@/assets/images/pet/cat/care_health3.webp'),
    require('@/assets/images/pet/cat/care_health4.webp'),
    require('@/assets/images/pet/cat/care_health5.webp'),
    require('@/assets/images/pet/cat/care_health6.webp'),
  ],
  mood: [
    require('@/assets/images/pet/cat/care_mood0.webp'),
    require('@/assets/images/pet/cat/care_mood1.webp'),
    require('@/assets/images/pet/cat/care_mood2.webp'),
    require('@/assets/images/pet/cat/care_mood3.webp'),
    require('@/assets/images/pet/cat/care_mood4.webp'),
    require('@/assets/images/pet/cat/care_mood5.webp'),
    require('@/assets/images/pet/cat/care_mood6.webp'),
  ],
  weight: [
    require('@/assets/images/pet/cat/care_weight0.webp'),
    require('@/assets/images/pet/cat/care_weight1.webp'),
    require('@/assets/images/pet/cat/care_weight2.webp'),
    require('@/assets/images/pet/cat/care_weight3.webp'),
    require('@/assets/images/pet/cat/care_weight4.webp'),
    require('@/assets/images/pet/cat/care_weight5.webp'),
    require('@/assets/images/pet/cat/care_weight6.webp'),
  ],
};
