import type { GameDefinition, GameSlug, PlatformId } from '../types';

export const PLATFORM_LABELS: Record<PlatformId, string> = {
  web: 'Web',
  telegram: 'TG',
  vk: 'VK',
  ok: 'OK',
  facebook: 'Facebook',
};

export const GAMES: GameDefinition[] = [
  {
    slug: '3-minute-brain-check',
    order: 1,
    name: '3‑Minute Brain Check',
    eyebrow: 'Quick profile',
    hook: 'Check your brain in 3 minutes',
    rule: 'Four short rounds: memory, attention, speed and control.',
    distribution: '“My profile today” + result comparison',
    platforms: ['vk', 'telegram', 'web', 'facebook'],
    accent: '#fbbf24',
    accent2: '#14b8a6',
    glyph: '◎',
  },
  {
    slug: 'schulte-speed',
    order: 2,
    name: 'Schulte Speed',
    eyebrow: 'Visual search',
    hook: 'Schulte table',
    rule: 'Tap the numbers from 1 to 25 in order as fast as you can.',
    distribution: 'Time in seconds + daily leaderboard',
    platforms: ['vk', 'telegram', 'ok', 'web'],
    accent: '#667eea',
    accent2: '#764ba2',
    glyph: '25',
    lowerIsBetter: true,
  },
  {
    slug: 'reaction-duel',
    order: 3,
    name: 'Reaction Duel',
    eyebrow: 'Response speed',
    hook: 'Reaction test',
    rule: 'Wait for the signal and tap after the flash. Early taps add a penalty.',
    distribution: '“Beat my 247 ms” — async challenge',
    platforms: ['vk', 'telegram', 'ok', 'facebook'],
    accent: '#fdc830',
    accent2: '#f37335',
    glyph: '⚡',
    lowerIsBetter: true,
  },
  {
    slug: 'memory-matrix',
    order: 4,
    name: 'Memory Matrix',
    eyebrow: 'Visual memory',
    hook: 'Memory matrix',
    rule: 'Remember the highlighted cells and recreate the pattern.',
    distribution: 'Grid size + correct-round streak',
    platforms: ['vk', 'telegram', 'web', 'facebook'],
    accent: '#8e2de2',
    accent2: '#4a00e0',
    glyph: '▦',
  },
  {
    slug: 'stroop-challenge',
    order: 5,
    name: 'Stroop Challenge',
    eyebrow: 'Response inhibition',
    hook: 'Color versus word',
    rule: 'Choose the ink color, not the meaning of the written word.',
    distribution: 'Errors + speed + weekly tournament',
    platforms: ['vk', 'telegram', 'ok', 'web'],
    accent: '#fc466b',
    accent2: '#3f5efb',
    glyph: 'Aa',
  },
  {
    slug: 'n-back-daily',
    order: 6,
    name: 'N‑Back Daily',
    eyebrow: 'Working memory',
    hook: 'A serious daily workout',
    rule: 'Mark the position that matches the one shown N steps earlier.',
    distribution: 'N level + day streak + full program',
    platforms: ['telegram', 'web', 'vk'],
    accent: '#5b86e5',
    accent2: '#36d1dc',
    glyph: 'N−2',
  },
  {
    slug: 'impulse-control',
    order: 7,
    name: 'Impulse Control',
    eyebrow: 'Go / No‑Go',
    hook: 'Tap — but know when to stop',
    rule: 'Tap the green signal and do nothing when it turns red.',
    distribution: 'Number of impulsive errors',
    platforms: ['vk', 'telegram', 'web'],
    accent: '#11998e',
    accent2: '#38ef7d',
    glyph: '●',
  },
  {
    slug: 'tower-puzzle',
    order: 8,
    name: 'Tower Puzzle',
    eyebrow: 'Planning',
    hook: 'Tower of Hanoi',
    rule: 'Move the tower without placing a larger disc on a smaller one.',
    distribution: 'Optimal-move ratio + daily puzzle',
    platforms: ['vk', 'telegram', 'ok', 'facebook'],
    accent: '#a8c0ff',
    accent2: '#3f2b96',
    glyph: '△',
  },
  {
    slug: 'focus-defender',
    order: 9,
    name: 'Focus Defender',
    eyebrow: 'Flanker task',
    hook: 'The center arrow versus distraction',
    rule: 'Identify the direction of the center arrow and ignore its neighbors.',
    distribution: '60 seconds without an error + friend challenge',
    platforms: ['vk', 'telegram', 'web', 'facebook'],
    accent: '#94a3b8',
    accent2: '#334155',
    glyph: '≪≫',
  },
];

export const GAME_BY_SLUG = Object.fromEntries(GAMES.map((game) => [game.slug, game])) as Record<GameSlug, GameDefinition>;

export function isGameSlug(value: string): value is GameSlug {
  return value in GAME_BY_SLUG;
}
