// Cloze-фразы (Полиглот TIER 1 п.4, v1.29.0) — «пропущенное слово во фразе».
// answerEn = en-ключ записи TRANSLATION_VOCAB; ответ на языке = entry[lang],
// дистракторы — слова той же категории (entry.cat) на том же языке.
//
// ⚠️ Правила составления (НЕ нарушать при добавлении фраз):
// 1. Ответ грамматичен В СЛОВАРНОЙ ФОРМЕ (как лежит в словаре): для ru/de/es/pt/hi
//    выбраны конструкции без падежной/родовой деформации пропуска
//    (ru: «на столе лежит ___», глаголы наст. вр. 3 л.; de: артикль в тексте фразы
//    согласован с родом ответа; hi: глагол согласован с родом ответа).
// 2. Глаголы — фразы под инфинитив/словарную форму (ru «покупать» = несов. вид).
// 3. answerEn обязан существовать в TRANSLATION_VOCAB (сверка при генерации — фраза
//    с неизвестным answerEn молча пропускается, см. cloze.tsx).
// Фразы НЕ переводы друг друга — каждый язык написан отдельно, уровень A1.

export interface ClozePhrase {
  text: string;     // фраза с ___ на языке lang
  answerEn: string; // en-ключ записи словаря
}

export const CLOZE_PHRASES: Record<string, ClozePhrase[]> = {
  en: [
    { text: 'I drink ___ every morning.', answerEn: 'coffee' },
    { text: 'The ___ is shining in the sky.', answerEn: 'sun' },
    { text: 'My ___ has four rooms.', answerEn: 'house' },
    { text: 'The cat drinks ___.', answerEn: 'milk' },
    { text: 'I am reading an interesting ___.', answerEn: 'book' },
    { text: 'The ___ is barking outside.', answerEn: 'dog' },
    { text: 'Open the ___, please.', answerEn: 'door' },
    { text: 'In winter we often see ___.', answerEn: 'snow' },
    { text: 'My younger ___ goes to school.', answerEn: 'brother' },
    { text: 'The fish lives in the ___.', answerEn: 'sea' },
    { text: 'I want ___ a new car.', answerEn: 'to buy' },
    { text: 'This bag is very ___.', answerEn: 'expensive' },
    { text: 'The opposite of hot is ___.', answerEn: 'cold' },
    { text: 'Look at the ___ — it is full tonight.', answerEn: 'moon' },
    { text: 'After the night comes the ___.', answerEn: 'morning' },
    { text: 'In the evening I like ___ books.', answerEn: 'to read' },
  ],
  ru: [
    { text: 'На столе лежит ___.', answerEn: 'book' },
    { text: 'Утром я пью ___.', answerEn: 'coffee' },
    { text: 'Ночью на небе светит ___.', answerEn: 'moon' },
    { text: 'Во дворе лает ___.', answerEn: 'dog' },
    { text: 'Зимой часто идёт ___.', answerEn: 'snow' },
    { text: 'В реке плавает ___.', answerEn: 'fish' },
    { text: 'У дома растёт высокое ___.', answerEn: 'tree' },
    { text: 'Мы идём ___ продукты.', answerEn: 'to buy' },
    { text: 'Вечером я люблю ___ книги.', answerEn: 'to read' },
    { text: '___ светит днём, а луна — ночью.', answerEn: 'sun' },
    { text: 'В этой комнате есть большое ___.', answerEn: 'window' },
    { text: 'По дороге едет ___.', answerEn: 'car' },
    { text: 'В зоопарке живёт большой ___.', answerEn: 'elephant' },
    { text: 'Мне нравится моя ___.', answerEn: 'work' },
    { text: 'Противоположность слову «горячий» — ___.', answerEn: 'cold' },
    { text: 'После ночи наступает ___.', answerEn: 'morning' },
  ],
  es: [
    { text: 'Por la mañana bebo ___.', answerEn: 'coffee' },
    { text: 'Quiero ___ un coche nuevo.', answerEn: 'to buy' },
    { text: 'Mi hermano sabe ___ muy rápido.', answerEn: 'to read' },
    { text: 'En invierno cae mucha ___.', answerEn: 'snow' },
    { text: 'No tengo ___ para comprar esto.', answerEn: 'money' },
    { text: '¿Quieres vino o ___?', answerEn: 'tea' },
    { text: 'Mi ___ tiene cuatro habitaciones.', answerEn: 'house' },
    { text: 'El gato bebe ___.', answerEn: 'milk' },
    { text: 'No encuentro mi ___.', answerEn: 'key' },
    { text: 'Después de la noche llega la ___.', answerEn: 'morning' },
    { text: 'Hoy hace mucho ___.', answerEn: 'wind' },
    { text: 'Voy a la ___ todos los días.', answerEn: 'school' },
    { text: 'El opuesto de caliente es ___.', answerEn: 'cold' },
    { text: 'Mi color favorito es el ___.', answerEn: 'blue' },
    { text: 'El ___ nada en el río.', answerEn: 'fish' },
    { text: 'Mi ___ pequeño va a la escuela.', answerEn: 'brother' },
  ],
  pt: [
    { text: 'De manhã bebo ___.', answerEn: 'coffee' },
    { text: 'O gato bebe ___.', answerEn: 'milk' },
    { text: 'No inverno cai muita ___.', answerEn: 'snow' },
    { text: 'Não tenho ___ para comprar isso.', answerEn: 'money' },
    { text: 'Quero ___ um carro novo.', answerEn: 'to buy' },
    { text: 'O ___ brilha no céu.', answerEn: 'sun' },
    { text: 'Minha ___ tem quatro quartos.', answerEn: 'house' },
    { text: 'O ___ late no quintal.', answerEn: 'dog' },
    { text: 'Em cima da mesa há um ___.', answerEn: 'book' },
    { text: 'O oposto de quente é ___.', answerEn: 'cold' },
    { text: 'Depois da noite vem a ___.', answerEn: 'morning' },
    { text: 'A ___ está cheia hoje.', answerEn: 'moon' },
    { text: 'Vou à ___ todos os dias.', answerEn: 'school' },
    { text: 'No rio nada um ___.', answerEn: 'fish' },
    { text: 'Hoje faz muito ___.', answerEn: 'wind' },
    { text: 'Meu ___ pequeno vai à escola.', answerEn: 'brother' },
  ],
  de: [
    { text: 'Ich trinke jeden Morgen ___.', answerEn: 'coffee' },
    { text: 'Die Katze trinkt ___.', answerEn: 'milk' },
    { text: 'Im Winter fällt viel ___.', answerEn: 'snow' },
    { text: 'Ich habe kein ___.', answerEn: 'money' },
    { text: 'Die ___ scheint am Himmel.', answerEn: 'sun' },
    { text: 'Der ___ bellt im Hof.', answerEn: 'dog' },
    { text: 'Mein ___ hat vier Zimmer.', answerEn: 'house' },
    { text: 'Ich möchte ein neues Auto ___.', answerEn: 'to buy' },
    { text: 'Am Abend mag ich ___.', answerEn: 'to read' },
    { text: 'Auf dem Tisch liegt ein ___.', answerEn: 'book' },
    { text: 'Das Gegenteil von heiß ist ___.', answerEn: 'cold' },
    { text: 'Nach der Nacht kommt der ___.', answerEn: 'morning' },
    { text: 'Der ___ ist heute voll.', answerEn: 'moon' },
    { text: 'Ich gehe jeden Tag zur ___.', answerEn: 'school' },
    { text: 'Im Fluss schwimmt ein ___.', answerEn: 'fish' },
    { text: 'Meine ___ ist sehr schön.', answerEn: 'flower' },
  ],
  zh: [
    { text: '我每天早上喝___。', answerEn: 'coffee' },
    { text: '猫喜欢喝___。', answerEn: 'milk' },
    { text: '冬天经常下___。', answerEn: 'snow' },
    { text: '我没有___买这个。', answerEn: 'money' },
    { text: '___在天上照耀。', answerEn: 'sun' },
    { text: '___在院子里叫。', answerEn: 'dog' },
    { text: '我的___有四个房间。', answerEn: 'house' },
    { text: '我想___一辆新车。', answerEn: 'to buy' },
    { text: '晚上我喜欢___书。', answerEn: 'to read' },
    { text: '桌子上有一本___。', answerEn: 'book' },
    { text: '热的反义词是___。', answerEn: 'cold' },
    { text: '夜晚之后是___。', answerEn: 'morning' },
    { text: '今晚的___很圆。', answerEn: 'moon' },
    { text: '我每天去___。', answerEn: 'school' },
    { text: '___在河里游。', answerEn: 'fish' },
    { text: '我有一个___。', answerEn: 'brother' },
  ],
  hi: [
    { text: 'मैं हर सुबह ___ पीता हूँ।', answerEn: 'coffee' },
    { text: 'बिल्ली ___ पीती है।', answerEn: 'milk' },
    { text: 'सर्दियों में ___ गिरती है।', answerEn: 'snow' },
    { text: 'मेरे पास ___ नहीं है।', answerEn: 'money' },
    { text: '___ आसमान में चमकता है।', answerEn: 'sun' },
    { text: '___ आँगन में भौंकता है।', answerEn: 'dog' },
    { text: 'मेरे ___ में चार कमरे हैं।', answerEn: 'house' },
    { text: 'मैं नई गाड़ी ___ चाहता हूँ।', answerEn: 'to buy' },
    { text: 'शाम को मुझे ___ पसंद है।', answerEn: 'to read' },
    { text: 'मेज़ पर एक ___ है।', answerEn: 'book' },
    { text: 'गरम का उल्टा ___ है।', answerEn: 'cold' },
    { text: 'रात के बाद ___ आती है।', answerEn: 'morning' },
    { text: 'आज ___ पूरा है।', answerEn: 'moon' },
    { text: 'मैं हर दिन ___ जाता हूँ।', answerEn: 'school' },
    { text: '___ नदी में तैरती है।', answerEn: 'fish' },
    { text: 'मेरा छोटा ___ स्कूल जाता है।', answerEn: 'brother' },
  ],
};
