// Cloze-фразы (Полиглот TIER 1 п.4, v1.29.0) — «пропущенное слово во фразе».
// answerEn = en-ключ записи TRANSLATION_VOCAB; ответ на языке = entry[lang],
// дистракторы — слова той же категории (entry.cat) на том же языке.
//
// ⚠️ Правила составления (НЕ нарушать при добавлении фраз):
// 1. Ответ грамматичен В СЛОВАРНОЙ ФОРМЕ (как лежит в словаре): для ru/de/es/pt/hi
//    выбраны конструкции без падежной/родовой деформации пропуска
//    (ru: «на столе лежит ___», глаголы наст. вр. 3 л.; de: артикль в тексте фразы
//    согласован с родом ответа; hi: глагол согласован с родом ответа).
// 2. Глаголы — фразы под инфинитив/словарную форму (ru «покупать» = несов. вид).
// 3. answerEn обязан существовать в TRANSLATION_VOCAB (сверка при генерации — фраза
//    с неизвестным answerEn молча пропускается, см. cloze.tsx).
// Фразы НЕ переводы друг друга — каждый язык написан отдельно, уровень A1.

export interface ClozePhrase {
  text: string;     // фраза с ___ на языке lang
  answerEn: string; // en-ключ записи словаря
}

export const CLOZE_PHRASES: Record<string, ClozePhrase[]> = {
  en: [
    { text: 'I drink ___ every morning.', answerEn: 'coffee' },
    { text: 'The ___ is shining in the sky.', answerEn: 'sun' },
    { text: 'My ___ has four rooms.', answerEn: 'house' },
    { text: 'The cat drinks ___.', answerEn: 'milk' },
    { text: 'I am reading an interesting ___.', answerEn: 'book' },
    { text: 'The ___ is barking outside.', answerEn: 'dog' },
    { text: 'Open the ___, please.', answerEn: 'door' },
    { text: 'In winter we often see ___.', answerEn: 'snow' },
    { text: 'My younger ___ goes to school.', answerEn: 'brother' },
    { text: 'The fish lives in the ___.', answerEn: 'sea' },
    { text: 'I want ___ a new car.', answerEn: 'to buy' },
    { text: 'This bag is very ___.', answerEn: 'expensive' },
    { text: 'The opposite of hot is ___.', answerEn: 'cold' },
    { text: 'Look at the ___ — it is full tonight.', answerEn: 'moon' },
    { text: 'After the night comes the ___.', answerEn: 'morning' },
    { text: 'In the evening I like ___ books.', answerEn: 'to read' },
    { text: 'I am thirsty — give me some ___.', answerEn: 'water' },
    { text: 'The ___ warms the whole room.', answerEn: 'fire' },
    { text: 'The first ___ appears in the evening sky.', answerEn: 'star' },
    { text: 'Take an umbrella, the ___ is heavy today.', answerEn: 'rain' },
    { text: 'She buys fresh ___ every morning.', answerEn: 'bread' },
    { text: 'There is a red ___ in the basket.', answerEn: 'apple' },
    { text: 'The ___ runs across the field.', answerEn: 'horse' },
    { text: 'A small grey ___ lives under the floor.', answerEn: 'mouse' },
    { text: 'We swim in the ___ every summer.', answerEn: 'river' },
    { text: 'The highest ___ is covered with snow.', answerEn: 'mountain' },
    { text: 'Mushrooms grow in the ___.', answerEn: 'forest' },
    { text: 'Put the plates on the ___.', answerEn: 'table' },
    { text: 'The ___ on the wall shows nine.', answerEn: 'clock' },
    { text: 'We buy vegetables at the ___.', answerEn: 'market' },
    { text: 'They took him to the ___.', answerEn: 'hospital' },
    { text: 'The lesson lasts one ___.', answerEn: 'hour' },
    { text: 'Children need ___ at least eight hours.', answerEn: 'to sleep' },
    { text: 'I want ___ a letter to my friend.', answerEn: 'to write' },
    { text: 'Please help me ___ this window.', answerEn: 'to open' },
    { text: 'This house is very ___.', answerEn: 'big' },
    { text: 'This train is very ___.', answerEn: 'fast' },
    { text: 'The floor in the kitchen is ___.', answerEn: 'clean' },
    { text: 'My grandfather is already very ___.', answerEn: 'old' },
    { text: 'I like listening to ___.', answerEn: 'music' },
  ],
  ru: [
    { text: 'На столе лежит ___.', answerEn: 'book' },
    { text: 'Утром я пью ___.', answerEn: 'coffee' },
    { text: 'Ночью на небе светит ___.', answerEn: 'moon' },
    { text: 'Во дворе лает ___.', answerEn: 'dog' },
    { text: 'Зимой часто идёт ___.', answerEn: 'snow' },
    { text: 'В реке плавает ___.', answerEn: 'fish' },
    { text: 'У дома растёт высокое ___.', answerEn: 'tree' },
    { text: 'Мы идём ___ продукты.', answerEn: 'to buy' },
    { text: 'Вечером я люблю ___ книги.', answerEn: 'to read' },
    { text: '___ светит днём, а луна — ночью.', answerEn: 'sun' },
    { text: 'В этой комнате есть большое ___.', answerEn: 'window' },
    { text: 'По дороге едет ___.', answerEn: 'car' },
    { text: 'В зоопарке живёт большой ___.', answerEn: 'elephant' },
    { text: 'Мне нравится моя ___.', answerEn: 'work' },
    { text: 'Противоположность слову «горячий» — ___.', answerEn: 'cold' },
    { text: 'После ночи наступает ___.', answerEn: 'morning' },
    { text: 'В стакане холодная ___.', answerEn: 'water' },
    { text: 'В печи горит ___.', answerEn: 'fire' },
    { text: 'Первая ___ загорается вечером.', answerEn: 'star' },
    { text: 'На улице идёт сильный ___.', answerEn: 'rain' },
    { text: 'Мама печёт вкусный ___.', answerEn: 'bread' },
    { text: 'В корзине лежит красное ___.', answerEn: 'apple' },
    { text: 'По полю бежит ___.', answerEn: 'horse' },
    { text: 'Под полом живёт серая ___.', answerEn: 'mouse' },
    { text: 'Через город течёт ___.', answerEn: 'river' },
    { text: 'Вдалеке видна высокая ___.', answerEn: 'mountain' },
    { text: 'За деревней начинается густой ___.', answerEn: 'forest' },
    { text: 'В комнате стоит деревянный ___.', answerEn: 'chair' },
    { text: 'На стене висят старые ___.', answerEn: 'clock' },
    { text: 'Наш ___ стоит на реке.', answerEn: 'city' },
    { text: 'Рядом с домом открылся новый ___.', answerEn: 'market' },
    { text: 'В нашем городе есть новая ___.', answerEn: 'hospital' },
    { text: 'Урок длится один ___.', answerEn: 'hour' },
    { text: 'Ребёнку нужно ___ восемь часов.', answerEn: 'to sleep' },
    { text: 'Я хочу ___ письмо другу.', answerEn: 'to write' },
    { text: 'Не забывай ___ окно по утрам.', answerEn: 'to open' },
    { text: 'Слон — очень ___ зверь.', answerEn: 'big' },
    { text: 'Этот поезд очень ___.', answerEn: 'fast' },
    { text: 'Пол в комнате совсем ___.', answerEn: 'clean' },
    { text: 'Мой дедушка уже очень ___.', answerEn: 'old' },
  ],
  es: [
    { text: 'Por la mañana bebo ___.', answerEn: 'coffee' },
    { text: 'Quiero ___ un coche nuevo.', answerEn: 'to buy' },
    { text: 'Mi hermano sabe ___ muy rápido.', answerEn: 'to read' },
    { text: 'En invierno cae mucha ___.', answerEn: 'snow' },
    { text: 'No tengo ___ para comprar esto.', answerEn: 'money' },
    { text: '¿Quieres vino o ___?', answerEn: 'tea' },
    { text: 'Mi ___ tiene cuatro habitaciones.', answerEn: 'house' },
    { text: 'El gato bebe ___.', answerEn: 'milk' },
    { text: 'No encuentro mi ___.', answerEn: 'key' },
    { text: 'Después de la noche llega la ___.', answerEn: 'morning' },
    { text: 'Hoy hace mucho ___.', answerEn: 'wind' },
    { text: 'Voy a la ___ todos los días.', answerEn: 'school' },
    { text: 'El opuesto de caliente es ___.', answerEn: 'cold' },
    { text: 'Mi color favorito es el ___.', answerEn: 'blue' },
    { text: 'El ___ nada en el río.', answerEn: 'fish' },
    { text: 'Mi ___ pequeño va a la escuela.', answerEn: 'brother' },
    { text: 'En el vaso hay ___ fría.', answerEn: 'water' },
    { text: 'En la chimenea arde el ___.', answerEn: 'fire' },
    { text: 'La primera ___ aparece por la tarde.', answerEn: 'star' },
    { text: 'Hoy cae mucha ___.', answerEn: 'rain' },
    { text: 'Mi madre hace ___ todos los días.', answerEn: 'bread' },
    { text: 'En la cesta hay una ___ roja.', answerEn: 'apple' },
    { text: 'Por el campo corre un ___.', answerEn: 'horse' },
    { text: 'Debajo del suelo vive un ___.', answerEn: 'mouse' },
    { text: 'Por la ciudad pasa un ___.', answerEn: 'river' },
    { text: 'A lo lejos se ve una ___ alta.', answerEn: 'mountain' },
    { text: 'Detrás del pueblo empieza el ___.', answerEn: 'forest' },
    { text: 'En la cocina hay una ___ de madera.', answerEn: 'table' },
    { text: 'El ___ de la pared marca las nueve.', answerEn: 'clock' },
    { text: 'Compramos verduras en el ___.', answerEn: 'market' },
    { text: 'Lo llevaron al ___.', answerEn: 'hospital' },
    { text: 'La clase dura una ___.', answerEn: 'hour' },
    { text: 'Los niños necesitan ___ ocho horas.', answerEn: 'to sleep' },
    { text: 'Quiero ___ una carta a mi amigo.', answerEn: 'to write' },
    { text: 'Ayúdame a ___ la ventana.', answerEn: 'to open' },
    { text: 'Esta casa es muy ___.', answerEn: 'big' },
    { text: 'Este tren es muy ___.', answerEn: 'fast' },
    { text: 'El suelo de la cocina está ___.', answerEn: 'clean' },
    { text: 'Mi abuelo ya es muy ___.', answerEn: 'old' },
    { text: 'La ___ es mi asignatura favorita.', answerEn: 'music' },
  ],
  pt: [
    { text: 'De manhã bebo ___.', answerEn: 'coffee' },
    { text: 'O gato bebe ___.', answerEn: 'milk' },
    { text: 'No inverno cai muita ___.', answerEn: 'snow' },
    { text: 'Não tenho ___ para comprar isso.', answerEn: 'money' },
    { text: 'Quero ___ um carro novo.', answerEn: 'to buy' },
    { text: 'O ___ brilha no céu.', answerEn: 'sun' },
    { text: 'Minha ___ tem quatro quartos.', answerEn: 'house' },
    { text: 'O ___ late no quintal.', answerEn: 'dog' },
    { text: 'Em cima da mesa há um ___.', answerEn: 'book' },
    { text: 'O oposto de quente é ___.', answerEn: 'cold' },
    { text: 'Depois da noite vem a ___.', answerEn: 'morning' },
    { text: 'A ___ está cheia hoje.', answerEn: 'moon' },
    { text: 'Vou à ___ todos os dias.', answerEn: 'school' },
    { text: 'No rio nada um ___.', answerEn: 'fish' },
    { text: 'Hoje faz muito ___.', answerEn: 'wind' },
    { text: 'Meu ___ pequeno vai à escola.', answerEn: 'brother' },
    { text: 'No copo há ___ fria.', answerEn: 'water' },
    { text: 'Na lareira arde o ___.', answerEn: 'fire' },
    { text: 'À noite aparece a primeira ___.', answerEn: 'star' },
    { text: 'Hoje cai muita ___.', answerEn: 'rain' },
    { text: 'A minha mãe faz ___ todos os dias.', answerEn: 'bread' },
    { text: 'No cesto há uma ___ vermelha.', answerEn: 'apple' },
    { text: 'Pelo campo corre um ___.', answerEn: 'horse' },
    { text: 'Debaixo do chão vive um ___.', answerEn: 'mouse' },
    { text: 'Pela cidade passa um ___.', answerEn: 'river' },
    { text: 'Ao longe vê-se uma ___ alta.', answerEn: 'mountain' },
    { text: 'Atrás da aldeia começa a ___.', answerEn: 'forest' },
    { text: 'Na cozinha há uma ___ de madeira.', answerEn: 'table' },
    { text: 'O ___ na parede marca nove horas.', answerEn: 'clock' },
    { text: 'Compramos legumes no ___.', answerEn: 'market' },
    { text: 'Levaram-no ao ___.', answerEn: 'hospital' },
    { text: 'A aula dura uma ___.', answerEn: 'hour' },
    { text: 'As crianças precisam de ___ oito horas.', answerEn: 'to sleep' },
    { text: 'Quero ___ uma carta ao meu amigo.', answerEn: 'to write' },
    { text: 'Ajuda-me a ___ a janela.', answerEn: 'to open' },
    { text: 'Esta casa é muito ___.', answerEn: 'big' },
    { text: 'Este comboio é muito ___.', answerEn: 'fast' },
    { text: 'O chão da cozinha está ___.', answerEn: 'clean' },
    { text: 'O meu avô já é muito ___.', answerEn: 'old' },
    { text: 'Gosto de ouvir ___.', answerEn: 'music' },
  ],
  de: [
    { text: 'Ich trinke jeden Morgen ___.', answerEn: 'coffee' },
    { text: 'Die Katze trinkt ___.', answerEn: 'milk' },
    { text: 'Im Winter fällt viel ___.', answerEn: 'snow' },
    { text: 'Ich habe kein ___.', answerEn: 'money' },
    { text: 'Die ___ scheint am Himmel.', answerEn: 'sun' },
    { text: 'Der ___ bellt im Hof.', answerEn: 'dog' },
    { text: 'Mein ___ hat vier Zimmer.', answerEn: 'house' },
    { text: 'Ich möchte ein neues Auto ___.', answerEn: 'to buy' },
    { text: 'Am Abend mag ich ___.', answerEn: 'to read' },
    { text: 'Auf dem Tisch liegt ein ___.', answerEn: 'book' },
    { text: 'Das Gegenteil von heiß ist ___.', answerEn: 'cold' },
    { text: 'Nach der Nacht kommt der ___.', answerEn: 'morning' },
    { text: 'Der ___ ist heute voll.', answerEn: 'moon' },
    { text: 'Ich gehe jeden Tag zur ___.', answerEn: 'school' },
    { text: 'Im Fluss schwimmt ein ___.', answerEn: 'fish' },
    { text: 'Meine ___ ist sehr schön.', answerEn: 'flower' },
    { text: 'Im Glas ist kaltes ___.', answerEn: 'water' },
    { text: 'Im Ofen brennt das ___.', answerEn: 'fire' },
    { text: 'Am Abend erscheint der erste ___.', answerEn: 'star' },
    { text: 'Heute fällt viel ___.', answerEn: 'rain' },
    { text: 'Meine Mutter backt jeden Tag ___.', answerEn: 'bread' },
    { text: 'Im Korb liegt ein roter ___.', answerEn: 'apple' },
    { text: 'Über das Feld läuft ein ___.', answerEn: 'horse' },
    { text: 'Unter dem Boden lebt eine ___.', answerEn: 'mouse' },
    { text: 'Durch die Stadt fließt ein ___.', answerEn: 'river' },
    { text: 'In der Ferne sieht man einen hohen ___.', answerEn: 'mountain' },
    { text: 'Hinter dem Dorf beginnt der ___.', answerEn: 'forest' },
    { text: 'In der Küche steht ein ___ aus Holz.', answerEn: 'table' },
    { text: 'Die ___ an der Wand zeigt neun.', answerEn: 'clock' },
    { text: 'Wir kaufen Gemüse auf dem ___.', answerEn: 'market' },
    { text: 'Man brachte ihn ins ___.', answerEn: 'hospital' },
    { text: 'Der Unterricht dauert eine ___.', answerEn: 'hour' },
    { text: 'Kinder müssen acht Stunden ___.', answerEn: 'to sleep' },
    { text: 'Ich möchte meinem Freund einen Brief ___.', answerEn: 'to write' },
    { text: 'Hilf mir bitte, das Fenster zu ___.', answerEn: 'to open' },
    { text: 'Dieses Haus ist sehr ___.', answerEn: 'big' },
    { text: 'Dieser Zug ist sehr ___.', answerEn: 'fast' },
    { text: 'Der Boden in der Küche ist ___.', answerEn: 'clean' },
    { text: 'Mein Großvater ist schon sehr ___.', answerEn: 'old' },
    { text: 'Ich höre gern ___.', answerEn: 'music' },
  ],
  zh: [
    { text: '我每天早上喝___。', answerEn: 'coffee' },
    { text: '猫喜欢喝___。', answerEn: 'milk' },
    { text: '冬天经常下___。', answerEn: 'snow' },
    { text: '我没有___买这个。', answerEn: 'money' },
    { text: '___在天上照耀。', answerEn: 'sun' },
    { text: '___在院子里叫。', answerEn: 'dog' },
    { text: '我的___有四个房间。', answerEn: 'house' },
    { text: '我想___一辆新车。', answerEn: 'to buy' },
    { text: '晚上我喜欢___书。', answerEn: 'to read' },
    { text: '桌子上有一本___。', answerEn: 'book' },
    { text: '热的反义词是___。', answerEn: 'cold' },
    { text: '夜晚之后是___。', answerEn: 'morning' },
    { text: '今晚的___很圆。', answerEn: 'moon' },
    { text: '我每天去___。', answerEn: 'school' },
    { text: '___在河里游。', answerEn: 'fish' },
    { text: '我有一个___。', answerEn: 'brother' },
    { text: '杯子里有冷___。', answerEn: 'water' },
    { text: '炉子里烧着___。', answerEn: 'fire' },
    { text: '晚上出现第一颗___。', answerEn: 'star' },
    { text: '今天下了很大的___。', answerEn: 'rain' },
    { text: '妈妈每天做___。', answerEn: 'bread' },
    { text: '篮子里有一个红色的___。', answerEn: 'apple' },
    { text: '田野上跑着一匹___。', answerEn: 'horse' },
    { text: '地板下面住着一只___。', answerEn: 'mouse' },
    { text: '城市里流过一条___。', answerEn: 'river' },
    { text: '远处能看到一座高___。', answerEn: 'mountain' },
    { text: '村子后面是一片___。', answerEn: 'forest' },
    { text: '厨房里有一张木头___。', answerEn: 'table' },
    { text: '墙上的___指着九点。', answerEn: 'clock' },
    { text: '我们在___买蔬菜。', answerEn: 'market' },
    { text: '他被送到了___。', answerEn: 'hospital' },
    { text: '一节课上一个___。', answerEn: 'hour' },
    { text: '孩子每天要___八个小时。', answerEn: 'to sleep' },
    { text: '我想给朋友___一封信。', answerEn: 'to write' },
    { text: '请帮我___窗户。', answerEn: 'to open' },
    { text: '这座房子非常___。', answerEn: 'big' },
    { text: '这列火车非常___。', answerEn: 'fast' },
    { text: '厨房的地板很___。', answerEn: 'clean' },
    { text: '这栋楼已经很___了。', answerEn: 'old' },
    { text: '我喜欢听___。', answerEn: 'music' },
  ],
  hi: [
    { text: 'मैं हर सुबह ___ पीता हूँ।', answerEn: 'coffee' },
    { text: 'बिल्ली ___ पीती है।', answerEn: 'milk' },
    { text: 'सर्दियों में ___ गिरती है।', answerEn: 'snow' },
    { text: 'मेरे पास ___ नहीं है।', answerEn: 'money' },
    { text: '___ आसमान में चमकता है।', answerEn: 'sun' },
    { text: '___ आँगन में भौंकता है।', answerEn: 'dog' },
    { text: 'मेरे ___ में चार कमरे हैं।', answerEn: 'house' },
    { text: 'मैं नई गाड़ी ___ चाहता हूँ।', answerEn: 'to buy' },
    { text: 'शाम को मुझे ___ पसंद है।', answerEn: 'to read' },
    { text: 'मेज़ पर एक ___ है।', answerEn: 'book' },
    { text: 'गरम का उल्टा ___ है।', answerEn: 'cold' },
    { text: 'रात के बाद ___ आती है।', answerEn: 'morning' },
    { text: 'आज ___ पूरा है।', answerEn: 'moon' },
    { text: 'मैं हर दिन ___ जाता हूँ।', answerEn: 'school' },
    { text: '___ नदी में तैरती है।', answerEn: 'fish' },
    { text: 'मेरा छोटा ___ स्कूल जाता है।', answerEn: 'brother' },
    { text: 'गिलास में ठंडा ___ है।', answerEn: 'water' },
    { text: 'चूल्हे में ___ जल रही है।', answerEn: 'fire' },
    { text: 'शाम को पहला ___ दिखता है।', answerEn: 'star' },
    { text: 'आज बहुत ___ हो रही है।', answerEn: 'rain' },
    { text: 'माँ हर दिन ___ बनाती है।', answerEn: 'bread' },
    { text: 'टोकरी में लाल ___ रखा है।', answerEn: 'apple' },
    { text: 'खेत में ___ दौड़ रहा है।', answerEn: 'horse' },
    { text: 'फ़र्श के नीचे ___ रहता है।', answerEn: 'mouse' },
    { text: 'शहर से ___ बहती है।', answerEn: 'river' },
    { text: 'दूर एक ऊँचा ___ दिखता है।', answerEn: 'mountain' },
    { text: 'गाँव के पीछे ___ शुरू होता है।', answerEn: 'forest' },
    { text: 'रसोई में लकड़ी की ___ रखी है।', answerEn: 'table' },
    { text: 'दीवार पर ___ नौ बजा रही है।', answerEn: 'clock' },
    { text: 'हम सब्ज़ी ___ से लाते हैं।', answerEn: 'market' },
    { text: 'उसे ___ ले गए।', answerEn: 'hospital' },
    { text: 'पाठ एक ___ चलता है।', answerEn: 'hour' },
    { text: 'बच्चों को आठ घंटे ___ चाहिए।', answerEn: 'to sleep' },
    { text: 'मैं दोस्त को चिट्ठी ___ चाहता हूँ।', answerEn: 'to write' },
    { text: 'दरवाज़ा ___ आसान है।', answerEn: 'to open' },
    { text: 'यह घर बहुत ___ है।', answerEn: 'big' },
    { text: 'यह रेलगाड़ी बहुत ___ है।', answerEn: 'fast' },
    { text: 'रसोई का फ़र्श ___ है।', answerEn: 'clean' },
    { text: 'यह मकान बहुत ___ है।', answerEn: 'old' },
    { text: 'मुझे ___ सुनना पसंद है।', answerEn: 'music' },
  ],
};
