// Кастомные иконки игр (Nano Banana 2, единый глянец-3D мини-тайл, 256px PNG).
// Реестр id → картинка. GameCard подставляет её вместо Ionicons (фолбэк — Ionicons,
// если для id нет картинки), поэтому раскатка безопасна и постепенна.
export const GAME_ICONS: Record<string, any> = {
  anagrams: require('../../assets/images/game_icons/anagrams.png'),
  ant: require('../../assets/images/game_icons/ant.png'),
  attention_conflict: require('../../assets/images/game_icons/attention_conflict.png'),
  bart: require('../../assets/images/game_icons/bart.png'),
  choice_rt: require('../../assets/images/game_icons/choice_rt.png'),
  cloze: require('../../assets/images/game_icons/cloze.png'),
  corsi: require('../../assets/images/game_icons/corsi.png'),
  counter: require('../../assets/images/game_icons/counter.png'),
  cpt: require('../../assets/images/game_icons/cpt.png'),
  digit_span: require('../../assets/images/game_icons/digit_span.png'),
  eye_gym: require('../../assets/images/game_icons/eye_gym.png'),
  find_differences: require('../../assets/images/game_icons/find_differences.png'),
  flanker: require('../../assets/images/game_icons/flanker.png'),
  go_no_go: require('../../assets/images/game_icons/go_no_go.png'),
  goods_sort: require('../../assets/images/game_icons/goods_sort.png'),
  hanoi: require('../../assets/images/game_icons/hanoi.png'),
  inhibition: require('../../assets/images/game_icons/inhibition.png'),
  iowa: require('../../assets/images/game_icons/iowa.png'),
  lexical_decision: require('../../assets/images/game_icons/lexical_decision.png'),
  math_sprint: require('../../assets/images/game_icons/math_sprint.png'),
  memory_matrix: require('../../assets/images/game_icons/memory_matrix.png'),
  mental_rotation: require('../../assets/images/game_icons/mental_rotation.png'),
  mnemonics: require('../../assets/images/game_icons/mnemonics.png'),
  n_back: require('../../assets/images/game_icons/n_back.png'),
  number_bonds: require('../../assets/images/game_icons/number_bonds.png'),
  ospan: require('../../assets/images/game_icons/ospan.png'),
  pattern: require('../../assets/images/game_icons/pattern.png'),
  phonemic_fluency: require('../../assets/images/game_icons/phonemic_fluency.png'),
  picture_pairs: require('../../assets/images/game_icons/picture_pairs.png'),
  posner: require('../../assets/images/game_icons/posner.png'),
  prl: require('../../assets/images/game_icons/prl.png'),
  proofreading: require('../../assets/images/game_icons/proofreading.png'),
  reading_span: require('../../assets/images/game_icons/reading_span.png'),
  rmet: require('../../assets/images/game_icons/rmet.png'),
  schulte_table: require('../../assets/images/game_icons/schulte_table.png'),
  sdmt: require('../../assets/images/game_icons/sdmt.png'),
  semantic_sort: require('../../assets/images/game_icons/semantic_sort.png'),
  set_game: require('../../assets/images/game_icons/set_game.png'),
  simon: require('../../assets/images/game_icons/simon.png'),
  span_group: require('../../assets/images/game_icons/span_group.png'),
  spatial_span: require('../../assets/images/game_icons/spatial_span.png'),
  stop_signal: require('../../assets/images/game_icons/stop_signal.png'),
  story_recall: require('../../assets/images/game_icons/story_recall.png'),
  stroop: require('../../assets/images/game_icons/stroop.png'),
  stroop_emotional: require('../../assets/images/game_icons/stroop_emotional.png'),
  sudoku: require('../../assets/images/game_icons/sudoku.png'),
  switching_task: require('../../assets/images/game_icons/switching_task.png'),
  targets: require('../../assets/images/game_icons/targets.png'),
  tower_london: require('../../assets/images/game_icons/tower_london.png'),
  trail_making: require('../../assets/images/game_icons/trail_making.png'),
  visual_search: require('../../assets/images/game_icons/visual_search.png'),
  vocab_srs: require('../../assets/images/game_icons/vocab_srs.png'),
  wcst: require('../../assets/images/game_icons/wcst.png'),
  word_pairs: require('../../assets/images/game_icons/word_pairs.png'),
};

/** Кастомная иконка игры по id (undefined → GameCard покажет Ionicons-фолбэк). */
export function gameIcon(id?: string) {
  return id ? GAME_ICONS[id] : undefined;
}
